### ISSUE TITLE
Landscape Mode

### ISSUE THREAD

**Issue by GolfBails** [udacity/Court-Counter#5]
I'm new to all of this. Can someone tell me why the code doesn't display properly in landscape mode and what can be done to correct it?

**Comment by KaterynaS** [comment]
Here is the explanation and fix https://medium.com/androiddevelopers/viewmodels-a-simple-example-ed5ac416317e

**Comment by LaszloLajosT** [comment]
Hi,

Thank you the link @KaterynaS !
I tried to do my best to understand the article. 
But still I am a bit confused. So the ViewModel should fix the landscape bug? 
I tried to implement to my code but when I rotate my phone it looks like the same like before. Did I miss anything?
Here is my project:
[project:](https://github.com/LaszloLajosT/CourtCounter.git)

Because I don't see any difference, I thought I can "fix" it if I use ScrollView( I already used it once for my first Simple Screen App) but I've got errors and it looks like my XML file here is too complicated :)

Update:
Sorry, my late reaction, I didn't see any notification and I was busy continue my study with full time job. I double checked my link and I fixed the link issue.
Good to come back, I plan to look at this again during the weekend.

**Comment by zawawimanja** [comment]
@LaszloLajosT where is ur project I cannot see it?

**Comment by LaszloLajosT** [comment]
A few months later, I came back to the link what @KaterynaS  shared here.
I started to change my code and use ViewModel. I don't know why but I thought ViewModel will also fix my layout issue if I rotate my phone. Well, that is an another task to do now.


I can tell the ViewModel works fine, and you can find my code [here.](https://github.com/LaszloLajosT/Udacity-Practice-CourtCounter).

**Comment by kt-aakash** [comment]
Hey guys, I have implemented the same using ConstraintLayout. Incase anyone here is intrested, feel free to checkout 

[Court-Counter](https://github.com/kt20162/Court-Counter-App)

**Comment by LaszloLajosT** [comment]
Thank you @kt20162 .
Your link doesn't work. I think this is the original [link for your project](https://github.com/kt20162/Court-Counter-App)

**Comment by kt-aakash** [comment]
Thanks @LaszloLajosT for the correction. I have modified my post to reflect the right link.
